[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Nazarii Bardiuk <nazarii@bardiuk.com>"]
edition = "2018"

[dependencies]
rayon = "1.1"
itertools = "0.8.2"
regex = "1.3.1"
num-integer = "0.1.41"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "bench"
harness = false
