name:                aoc2015
version:             0.1.0.0
github:              "nbardiuk/adventofcode"
license:             BSD3
author:              "Nazarii Bardiuk"
maintainer:          "nazarii@bardiuk.com"
copyright:           "2019 Nazarii Bardiuk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nbardiuk/aoc#readme>

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - cryptohash
  - megaparsec

library:
  source-dirs: src

tests:
  test:
    main: test.hs
    source-dirs:
      - test
    ghc-options:
      - -O3
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aoc2015
      - tasty
      - tasty-hspec
      - tasty-discover
